# Generated by Django 5.2.6 on 2025-11-24 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uID", models.IntegerField()),
                ("Name", models.CharField(max_length=30)),
                ("LineID", models.IntegerField(default=None)),
                ("LineInterchangeID", models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startID", models.IntegerField(default=None)),
                ("endID", models.IntegerField(default=None)),
                (
                    "purchaseDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("travelDate", models.DateTimeField()),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
